[tool.poetry]
name = "sw-eng-proj-1"
version = "0.1.0"
description = ""
authors = ["LukasOspelt <lukas.ospelt@adon.li>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
